#!/bin/sh

for dev in /sys/module/snd_*; do
	[ -w "$dev/parameters/power_save" ] || continue
	printf "Setting power savings for %s to %d..." "${dev##*/}" "1"
	echo "1" > "$dev/parameters/power_save" && echo Done. || echo Failed.
done

exit 0
